<?php

namespace Database\Seeders;

use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;

class UserSeeder extends Seeder
{
    public function run(): void
    {
        // ── Manager ───────────────────────────────────────────────
        User::firstOrCreate(
            ['employee_code' => 'QL00001'],
            [
                'name'                 => 'Quản Lý Hệ Thống',
                'email'                => 'manager@onamba.com.vn',
                'password'             => Hash::make('password'),
                'role'                 => 'manager',
                'department'           => 'Ban Giám đốc',
                'position'             => 'Quản lý hệ thống',
                'annual_leave_balance' => 15,
            ]
        );

        // ── Employees — sourced from onamba DB ─────────────────
        // Filter: active as of 2026-07-06 (terminatedate IS NULL or 0000-00-00 or >= today)
        // Excluded: System Admin department (legacy accounts)
        $employees = [
            ['name'=>'NGUYỄN THÀNH PHÚC','employee_code'=>'0010','email'=>null,'department'=>'Xưởng sản xuất'],
            ['name'=>'LÊ THỊ BÍCH THUẬN','employee_code'=>'0016','email'=>'lethibichthuan16@gmail.com','department'=>'Phòng Kế toán'],
            ['name'=>'NGUYỄN HỮU DƯƠNG','employee_code'=>'0026','email'=>'huuduong82@gmail.com','department'=>'Phòng IT'],
            ['name'=>'NGUYỄN THỊ MINH TÀI','employee_code'=>'0030','email'=>'nguyenthiminhtai.mtn@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'LÊ THỊ TÂM ĐAN','employee_code'=>'0079','email'=>null,'department'=>'Phòng QC'],
            ['name'=>'HUỲNH THỊ THUYỀN','employee_code'=>'0095','email'=>null,'department'=>'Phòng Nhân sự'],
            ['name'=>'HUỲNH THỊ BÍCH VÂN','employee_code'=>'0106','email'=>'huynhvan82@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'HỒ THỊ LAN','employee_code'=>'0178','email'=>null,'department'=>'Xưởng sản xuất'],
            ['name'=>'LƯƠNG THỊ VÂN','employee_code'=>'0187','email'=>null,'department'=>'Xưởng sản xuất'],
            ['name'=>'NGUYỄN HOÀNG ANH','employee_code'=>'0189','email'=>'nguyenhoanganh@onamba.com.vn','department'=>'Phòng Nhân sự'],
            ['name'=>'NGUYỄN THỊ MINH HÂN','employee_code'=>'0215','email'=>'minhhan10011982@gmail.com','department'=>'Phòng Kế toán'],
            ['name'=>'NGUYỄN THỊ THẮNG','employee_code'=>'0226','email'=>'thangnguyen19011979@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'VÕ THỊ KIM TUYỀN','employee_code'=>'0233','email'=>null,'department'=>'Xưởng sản xuất'],
            ['name'=>'LÊ THỊ HOÀNG HOA','employee_code'=>'0273','email'=>null,'department'=>'Phòng QC'],
            ['name'=>'PHẠM THỊ KIM CƯƠNG','employee_code'=>'0344','email'=>null,'department'=>'Xưởng sản xuất'],
            ['name'=>'VÕ THỊ BÍCH TRANG','employee_code'=>'0443','email'=>'vobichtrang77477@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'TRỊNH THỊ THU CÚC','employee_code'=>'0461','email'=>'trinhcuc88@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'DƯƠNG THỊ ÁNH DƯƠNG','employee_code'=>'0489','email'=>'duongthianhduong01011990@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'NGUYỄN THỊ TÀI','employee_code'=>'0716','email'=>null,'department'=>'Xưởng sản xuất'],
            ['name'=>'THỊ ÚT VÀNG','employee_code'=>'0835','email'=>null,'department'=>'Xưởng sản xuất'],
            ['name'=>'NGÔ QUỐC HƯNG','employee_code'=>'0893','email'=>'ngoquochung@onamba.com.vn','department'=>'Ban Giám đốc'],
            ['name'=>'NGUYỄN THỊ NGỌC DIỄM','employee_code'=>'0929','email'=>'nguyenvanphungvt22@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'NGUYỄN THỊ KIM HOA','employee_code'=>'0949','email'=>null,'department'=>'Xưởng sản xuất'],
            ['name'=>'PHÙNG THỊ NỮ','employee_code'=>'0960','email'=>'phungthinu7516@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'NGUYỄN THỊ HUYỀN TRANG','employee_code'=>'1017','email'=>null,'department'=>'Xưởng sản xuất'],
            ['name'=>'NGUYỄN ĐĂNG PHÚC','employee_code'=>'1039','email'=>'Nguyendangphuc3312@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'NGUYỄN THỊ KIM PHẤN','employee_code'=>'1052','email'=>'kimphan060890@gmail.com','department'=>'Phòng IT'],
            ['name'=>'PHẠM THỊ CHÚC ','employee_code'=>'1096','email'=>'phamthichuc1401@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'LÊ THỊ KIM THẮNG','employee_code'=>'1111','email'=>null,'department'=>'Xưởng sản xuất'],
            ['name'=>'PHAN THỊ LINH','employee_code'=>'1131','email'=>'phanthilinh1776@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'NGUYỄN THỊ THÚY LIỄU','employee_code'=>'1183','email'=>null,'department'=>'Phòng QC'],
            ['name'=>'NGUYỄN THỊ LỆ THU','employee_code'=>'1289','email'=>'lethanhphuoc1006@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'VÕ THỊ THU THỦY','employee_code'=>'1293','email'=>null,'department'=>'Xưởng sản xuất'],
            ['name'=>'HỨA THỊ NHANH','employee_code'=>'1394','email'=>null,'department'=>'Xưởng sản xuất'],
            ['name'=>'ĐẶNG THỊ ÂN PHÚC','employee_code'=>'1399','email'=>null,'department'=>'Xưởng sản xuất'],
            ['name'=>'NGUYỄN THỊ HỒNG PHƯƠNG','employee_code'=>'1450','email'=>null,'department'=>'Phòng QC'],
            ['name'=>'LÊ THỊ THANH TÂM','employee_code'=>'1468','email'=>'Lethithanhtam820929@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'MAI HỒNG EM','employee_code'=>'1564','email'=>null,'department'=>'Xưởng sản xuất'],
            ['name'=>'HÀ THỊ THANH THỰC ','employee_code'=>'1605','email'=>null,'department'=>'Phòng Logistics'],
            ['name'=>'NGUYỄN THỊ CÚC','employee_code'=>'1653','email'=>null,'department'=>'Phòng QC'],
            ['name'=>'NGUYỄN THỊ MỸ KHÁNH ','employee_code'=>'1696','email'=>null,'department'=>'Xưởng sản xuất'],
            ['name'=>'NGUYỄN VĂN HÙNG','employee_code'=>'1767','email'=>'hung47742@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'HỒ TRẦN TUẤN KIỆT','employee_code'=>'1770','email'=>null,'department'=>'Phòng IT'],
            ['name'=>'TẠ QUỐC HUY','employee_code'=>'1771','email'=>'taquochuy1980@gmail.com','department'=>'Phòng IT'],
            ['name'=>'NGUYỄN LỆ THU','employee_code'=>'1787','email'=>null,'department'=>'Xưởng sản xuất'],
            ['name'=>'ĐẶNG THU TRANG','employee_code'=>'1791','email'=>'Dangthutrang180892@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'LẠI THỊ KIM HUỆ','employee_code'=>'1802','email'=>null,'department'=>'Xưởng sản xuất'],
            ['name'=>'TRẦN CẢNH LƯỢNG','employee_code'=>'1909','email'=>'trancanhluong@onamba.com.vn','department'=>'Phòng Nhân sự'],
            ['name'=>'TỪ MỘNG THÙY','employee_code'=>'1936','email'=>null,'department'=>'Xưởng sản xuất'],
            ['name'=>'NGUYỄN THỊ PHƯƠNG','employee_code'=>'1937','email'=>null,'department'=>'Phòng Nhân sự'],
            ['name'=>'PHẠM VĂN ĐỒNG','employee_code'=>'1974','email'=>null,'department'=>'Xưởng sản xuất'],
            ['name'=>'LÊ THỊ YẾN TRINH','employee_code'=>'2001','email'=>null,'department'=>'Xưởng sản xuất'],
            ['name'=>'VÕ TRUNG TÍNH','employee_code'=>'2003','email'=>'trungtinh2903vo@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'THỊ BÉ TRÍ','employee_code'=>'2015','email'=>null,'department'=>'Xưởng sản xuất'],
            ['name'=>'NGUYỄN THỊ HẰNG','employee_code'=>'2020','email'=>'nguyenthihangbd140@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'TẠ QUỐC DUY','employee_code'=>'2029','email'=>'quocduy01981@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'NGUYỄN TRỌNG HƯNG','employee_code'=>'2033','email'=>null,'department'=>'Phòng IT'],
            ['name'=>'LÊ THỊ THANH NGA','employee_code'=>'2096','email'=>null,'department'=>'Phòng IT'],
            ['name'=>'DIỆP THANH TRỌNG','employee_code'=>'2107','email'=>'charles.diep.tt@gmail.com','department'=>'Phòng QC'],
            ['name'=>'NGUYỄN THỊ MAI THẢO','employee_code'=>'2108','email'=>null,'department'=>'Phòng Nhân sự'],
            ['name'=>'VÕ CẨM LINH','employee_code'=>'2133','email'=>null,'department'=>'Xưởng sản xuất'],
            ['name'=>'PHAN THỊ HỒNG HẠNH','employee_code'=>'2140','email'=>'Phanthihonghanh.020793@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'BÙI THỊ NGỌC BÍCH','employee_code'=>'2194','email'=>null,'department'=>'Phòng QC'],
            ['name'=>'NGUYỄN THỊ NGA','employee_code'=>'2199','email'=>null,'department'=>'Xưởng sản xuất'],
            ['name'=>'NGUYỄN VĂN SĨ','employee_code'=>'2221','email'=>'synguyen909@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'ĐINH THỊ ĐÀO','employee_code'=>'2264','email'=>null,'department'=>'Xưởng sản xuất'],
            ['name'=>'PHAN THỊ KIM TIẾN','employee_code'=>'2277','email'=>null,'department'=>'Phòng QC'],
            ['name'=>'PHAN THỊ THÚY NGUYÊN','employee_code'=>'2287','email'=>null,'department'=>'Xưởng sản xuất'],
            ['name'=>'LƯƠNG THÀNH LỢI','employee_code'=>'2291','email'=>null,'department'=>'Xưởng sản xuất'],
            ['name'=>'TRẦN KIM PHỤNG','employee_code'=>'2315','email'=>'trankimphungbd30@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'THỊ MỸ HOÀNG','employee_code'=>'2325','email'=>'thimyhoang1994@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'NGUYỄN THỊ THANH TUYỀN','employee_code'=>'2372','email'=>'thanhtuyennguyen021186@gmail.com','department'=>'Phòng QC'],
            ['name'=>'NGUYỄN BÁ TRƯỜNG','employee_code'=>'2376','email'=>'nguyenbatruong84@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'TRẦN QUANG MINH','employee_code'=>'2378','email'=>null,'department'=>'Xưởng sản xuất'],
            ['name'=>'NGUYỄN HOÀNG HẢI','employee_code'=>'2379','email'=>'hoanghai468482@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'NGUYỄN DUY PHI','employee_code'=>'2398','email'=>'nguyenduyphi1506@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'LÊ THỊ LÝ','employee_code'=>'2428','email'=>null,'department'=>'Phòng QC'],
            ['name'=>'NGUYỄN THỊ KIỀU','employee_code'=>'2539','email'=>null,'department'=>'Xưởng sản xuất'],
            ['name'=>'LÊ VĂN DƯƠNG','employee_code'=>'2569','email'=>'leduongth84@gmail.com','department'=>'Phòng IT'],
            ['name'=>'NGUYỄN THỊ KIM SON','employee_code'=>'2575','email'=>'kimsonnguyenthi97@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'PHAN THỊ TUYẾT MINH','employee_code'=>'2606','email'=>null,'department'=>'Xưởng sản xuất'],
            ['name'=>'PHẠM THỊ THU TRINH','employee_code'=>'2607','email'=>null,'department'=>'Xưởng sản xuất'],
            ['name'=>'NGUYỄN THỊ CẨM TIÊN','employee_code'=>'2619','email'=>null,'department'=>'Xưởng sản xuất'],
            ['name'=>'LÊ THỊ THANH HÒA','employee_code'=>'2624','email'=>null,'department'=>'Xưởng sản xuất'],
            ['name'=>'NGUYỄN THỊ THÙY TRANG','employee_code'=>'2629','email'=>'lethanhw1986@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'NGUYỄN THỊ HỨA','employee_code'=>'2639','email'=>'Nguyenthihua84@gmail.com','department'=>'Phòng QC'],
            ['name'=>'NGUYỄN KIM UYÊN','employee_code'=>'2660','email'=>null,'department'=>'Xưởng sản xuất'],
            ['name'=>'TRẦN THỊ THU THẢO','employee_code'=>'2662','email'=>null,'department'=>'Phòng QC'],
            ['name'=>'LƯƠNG THỊ LINH','employee_code'=>'2677','email'=>null,'department'=>'Xưởng sản xuất'],
            ['name'=>'LƯƠNG THỊ THU HẰNG','employee_code'=>'2679','email'=>null,'department'=>'Xưởng sản xuất'],
            ['name'=>'BÙI THỊ LỤA','employee_code'=>'2688','email'=>null,'department'=>'Xưởng sản xuất'],
            ['name'=>'THỊ TRÌ AN','employee_code'=>'2713','email'=>'antri4973@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'NGUYỄN THỊ YẾN CHI','employee_code'=>'2732','email'=>null,'department'=>'Xưởng sản xuất'],
            ['name'=>'PHAN THỊ HIỀN','employee_code'=>'2736','email'=>null,'department'=>'Phòng QC'],
            ['name'=>'LÊ THỊ THANH TỴ','employee_code'=>'2750','email'=>null,'department'=>'Phòng QC'],
            ['name'=>'NGUYỄN THỊ PHƯƠNG','employee_code'=>'2765','email'=>null,'department'=>'Phòng QC'],
            ['name'=>'NGUYỄN THỊ MỸ DIỄM','employee_code'=>'2784','email'=>null,'department'=>'Phòng QC'],
            ['name'=>'VŨ THỊ KIM HẠNH','employee_code'=>'2786','email'=>null,'department'=>'Phòng QC'],
            ['name'=>'HỒ THỊ PHƯƠNG HỒNG','employee_code'=>'2789','email'=>null,'department'=>'Xưởng sản xuất'],
            ['name'=>'HÀ THỊ MỸ TIÊN','employee_code'=>'2792','email'=>null,'department'=>'Phòng QC'],
            ['name'=>'ĐỖ THỊ MINH TÂM','employee_code'=>'2822','email'=>null,'department'=>'Xưởng sản xuất'],
            ['name'=>'ĐOÀN HƯNG','employee_code'=>'2859','email'=>'doanhung@onamba.com.vn','department'=>'Xưởng sản xuất'],
            ['name'=>'TRƯƠNG THÀNH TRUNG','employee_code'=>'2860','email'=>'nguyenthanhtrungbd30@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'LÊ HUỲNH VÂN','employee_code'=>'2864','email'=>null,'department'=>'Xưởng sản xuất'],
            ['name'=>'NGUYỄN THỊ HOAN','employee_code'=>'2865','email'=>null,'department'=>'Xưởng sản xuất'],
            ['name'=>'ĐÀO THỊ HẢO','employee_code'=>'2868','email'=>'daothihao0307@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'ĐÀM THỊ BÍCH','employee_code'=>'2902','email'=>null,'department'=>'Xưởng sản xuất'],
            ['name'=>'LÊ THỊ CÚC','employee_code'=>'2905','email'=>null,'department'=>'Phòng Nhân sự'],
            ['name'=>'NGUYỄN THỊ HIÊN','employee_code'=>'2913','email'=>null,'department'=>'Xưởng sản xuất'],
            ['name'=>'NGUYỄN THỊ KIM MẾN','employee_code'=>'2914','email'=>null,'department'=>'Xưởng sản xuất'],
            ['name'=>'MAI THỊ DIỄM TRANG','employee_code'=>'2922','email'=>null,'department'=>'Xưởng sản xuất'],
            ['name'=>'LÊ THỊ XUÂN NGHĨA','employee_code'=>'2927','email'=>null,'department'=>'Xưởng sản xuất'],
            ['name'=>'TRẦN THỊ THẢO','employee_code'=>'2929','email'=>null,'department'=>'Xưởng sản xuất'],
            ['name'=>'NGUYỄN THỊ THÚY AN','employee_code'=>'2941','email'=>null,'department'=>'Xưởng sản xuất'],
            ['name'=>'ĐỖ THỊ HỒNG NHẠN','employee_code'=>'2946','email'=>null,'department'=>'Phòng QC'],
            ['name'=>'NGUYỄN THỊ HOA','employee_code'=>'2948','email'=>null,'department'=>'Phòng QC'],
            ['name'=>'TRẦN THỊ THÚY','employee_code'=>'2950','email'=>null,'department'=>'Xưởng sản xuất'],
            ['name'=>'HUỲNH BÁ NHẪN ','employee_code'=>'2952','email'=>null,'department'=>'Xưởng sản xuất'],
            ['name'=>'NGUYỄN THỤY HOÀNG YẾN','employee_code'=>'2964','email'=>null,'department'=>'Phòng QC'],
            ['name'=>'LÝ THỊ TRƯỜNG AN','employee_code'=>'2965','email'=>null,'department'=>'Phòng QC'],
            ['name'=>'VÕ THỊ KIM HỒNG','employee_code'=>'2974','email'=>null,'department'=>'Xưởng sản xuất'],
            ['name'=>'PHAN THỊ THẢO','employee_code'=>'2996','email'=>null,'department'=>'Xưởng sản xuất'],
            ['name'=>'DIỆP THỊ NGỌC KHÁNH','employee_code'=>'2998','email'=>null,'department'=>'Phòng Nhân sự'],
            ['name'=>'PHAN THỊ MỸ DUNG','employee_code'=>'3003','email'=>null,'department'=>'Xưởng sản xuất'],
            ['name'=>'PHẠM THỊ MỸ AN','employee_code'=>'3012','email'=>null,'department'=>'Phòng Nhân sự'],
            ['name'=>'NGUYỄN THỊ TỊNH','employee_code'=>'3014','email'=>null,'department'=>'Phòng Nhân sự'],
            ['name'=>'LÊ THỊ KIM THI','employee_code'=>'3015','email'=>null,'department'=>'Phòng Nhân sự'],
            ['name'=>'TRẦN THỊ MỸ CHI','employee_code'=>'3016','email'=>null,'department'=>'Phòng Nhân sự'],
            ['name'=>'HUỲNH THỊ MỸ YÊN','employee_code'=>'3018','email'=>null,'department'=>'Phòng Nhân sự'],
            ['name'=>'NGUYỄN THỊ ÁI NGÂN','employee_code'=>'3021','email'=>null,'department'=>'Xưởng sản xuất'],
            ['name'=>'NGUYỄN THỊ HỒNG THỦY','employee_code'=>'3044','email'=>null,'department'=>'Phòng Nhân sự'],
            ['name'=>'DANH CÔNG HUẤN','employee_code'=>'3052','email'=>'conghuan0422@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'NGUYỄN HỒ TUYẾT TÂM','employee_code'=>'3074','email'=>null,'department'=>'Xưởng sản xuất'],
            ['name'=>'HUỲNH THỊ TƯỜNG VI','employee_code'=>'3081','email'=>null,'department'=>'Xưởng sản xuất'],
            ['name'=>'TRẦN THỊ NGUYÊN TRANG','employee_code'=>'3085','email'=>null,'department'=>'Xưởng sản xuất'],
            ['name'=>'NGÔ THỊ HỒNG','employee_code'=>'3110','email'=>null,'department'=>'Xưởng sản xuất'],
            ['name'=>'NGUYỄN THỊ NHẠN','employee_code'=>'3141','email'=>'mituot21081993@gmail.com','department'=>'Phòng QC'],
            ['name'=>'LÊ THỊ MỸ TRANG','employee_code'=>'3166','email'=>null,'department'=>'Xưởng sản xuất'],
            ['name'=>'LÊ THỊ KIỀU OANH','employee_code'=>'3180','email'=>'huynhnl8687@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'ĐOÀN THỊ TRÍ','employee_code'=>'3204','email'=>null,'department'=>'Xưởng sản xuất'],
            ['name'=>'VÕ THỊ LÊ','employee_code'=>'3289','email'=>'lephuoc110785@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'PHÙNG THỊ NI','employee_code'=>'3337','email'=>null,'department'=>'Xưởng sản xuất'],
            ['name'=>'TRẦN THỊ HUẾ TRÂN','employee_code'=>'3349','email'=>null,'department'=>'Xưởng sản xuất'],
            ['name'=>'NÔNG THỊ THỦY','employee_code'=>'3351','email'=>null,'department'=>'Xưởng sản xuất'],
            ['name'=>'NGUYỄN THỊ HOA','employee_code'=>'3358','email'=>null,'department'=>'Phòng QC'],
            ['name'=>'CHÂU NGỌC KHUYÊN','employee_code'=>'3389','email'=>'khuyenchau.15108418@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'TỐNG THỊ MỸ NGÂN','employee_code'=>'3419','email'=>'tranhoanghung1234567890@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'TRẦN DUY HẢI','employee_code'=>'3431','email'=>'tdhai091982@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'NGUYỄN MINH ÁI VY','employee_code'=>'3436','email'=>null,'department'=>'Xưởng sản xuất'],
            ['name'=>'LÊ THỊ BÍCH NGỌC','employee_code'=>'3456','email'=>'lethibichngocbdg30@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'VŨ THỊ HỒNG','employee_code'=>'3482','email'=>null,'department'=>'Xưởng sản xuất'],
            ['name'=>'LÊ THỊ TÚ ANH','employee_code'=>'3517','email'=>'dinhvanlonhoi1990@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'BÙI THỊ THƠM','employee_code'=>'3531','email'=>null,'department'=>'Xưởng sản xuất'],
            ['name'=>'NGUYỄN NGỌC PHƯƠNG MAI','employee_code'=>'3548','email'=>null,'department'=>'Phòng QC'],
            ['name'=>'ĐÀO THỊ AN','employee_code'=>'3557','email'=>null,'department'=>'Xưởng sản xuất'],
            ['name'=>'TRẦN THỊ DIỄM THÚY','employee_code'=>'3568','email'=>null,'department'=>'Xưởng sản xuất'],
            ['name'=>'HOÀNG THỊ HIỆN','employee_code'=>'3583','email'=>null,'department'=>'Xưởng sản xuất'],
            ['name'=>'NGUYỄN THỊ LƯỢM','employee_code'=>'3590','email'=>null,'department'=>'Xưởng sản xuất'],
            ['name'=>'NGUYỄN THỊ THÙY','employee_code'=>'3608','email'=>null,'department'=>'Phòng QC'],
            ['name'=>'NGUYỄN THỊ LỆ HÀ','employee_code'=>'3621','email'=>null,'department'=>'Phòng QC'],
            ['name'=>'LÊ KHẮC TÙNG','employee_code'=>'3623','email'=>null,'department'=>'Phòng QC'],
            ['name'=>'NGUYỄN VĂN TIẾNG','employee_code'=>'3624','email'=>null,'department'=>'Phòng QC'],
            ['name'=>'HUỲNH NGỌC LINH','employee_code'=>'3629','email'=>'Huynhngoclinh950105@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'HOÀNG THỊ NGỌC BÍCH','employee_code'=>'3650','email'=>null,'department'=>'Xưởng sản xuất'],
            ['name'=>'NGUYỄN VIỆT PHƯƠNG NGÂN','employee_code'=>'3659','email'=>null,'department'=>'Xưởng sản xuất'],
            ['name'=>'HUỲNH THỊ BẢO TRÂM','employee_code'=>'3673','email'=>null,'department'=>'Phòng QC'],
            ['name'=>'HOÀNG THỊ HOA','employee_code'=>'3683','email'=>null,'department'=>'Xưởng sản xuất'],
            ['name'=>'NGUYỄN THỊ PHƯƠNG','employee_code'=>'3700','email'=>'phuong1987bd@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'NGUYỄN THỊ NGỌC BÍCH','employee_code'=>'3712','email'=>null,'department'=>'Ban Giám đốc'],
            ['name'=>'LÊ THỊ DUNG','employee_code'=>'3720','email'=>null,'department'=>'Phòng QC'],
            ['name'=>'ĐÀO THỊ OANH','employee_code'=>'3722','email'=>null,'department'=>'Xưởng sản xuất'],
            ['name'=>'HỒ THỊ ÁNH HỒNG','employee_code'=>'3724','email'=>null,'department'=>'Xưởng sản xuất'],
            ['name'=>'NGUYỄN THỊ MỸ TRANG','employee_code'=>'3728','email'=>null,'department'=>'Phòng QC'],
            ['name'=>'NGUYỄN THỊ THANH HẰNG','employee_code'=>'3733','email'=>null,'department'=>'Xưởng sản xuất'],
            ['name'=>'LÊ THỊ HUỲNH NHƯ','employee_code'=>'3739','email'=>'phonglinh1995@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'NGUYỄN NHẤT TRUNG','employee_code'=>'3804','email'=>null,'department'=>'Xưởng sản xuất'],
            ['name'=>'NGUYỄN THỊ BÉ THẢO','employee_code'=>'3808','email'=>'nguyenthibethaoo22101995@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'LÊ QUỐC VIỆT','employee_code'=>'3855','email'=>null,'department'=>'Xưởng sản xuất'],
            ['name'=>'LÊ NGỌC QUYÊN','employee_code'=>'3872','email'=>null,'department'=>'Xưởng sản xuất'],
            ['name'=>'TRẦN THỊ NGỌC ĐÀO','employee_code'=>'3884','email'=>null,'department'=>'Xưởng sản xuất'],
            ['name'=>'DƯƠNG THỊ TUYẾT LAN','employee_code'=>'3889','email'=>null,'department'=>'Xưởng sản xuất'],
            ['name'=>'TRẦN KIM KIỀU','employee_code'=>'3896','email'=>null,'department'=>'Xưởng sản xuất'],
            ['name'=>'PHÙNG THANH NGA','employee_code'=>'3906','email'=>null,'department'=>'Phòng QC'],
            ['name'=>'NÔNG THỊ HUỆ','employee_code'=>'3916','email'=>'nongthihuebd12@gmail.com','department'=>'Phòng QC'],
            ['name'=>'THỊ TÚ ANH','employee_code'=>'3918','email'=>null,'department'=>'Xưởng sản xuất'],
            ['name'=>'NGUYỄN THỊ TRÀ MY','employee_code'=>'3941','email'=>null,'department'=>'Xưởng sản xuất'],
            ['name'=>'PHẠM THỊ THẢO','employee_code'=>'3994','email'=>'Phamthithao30081987@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'TRỊNH THỊ BÍCH MẬN','employee_code'=>'4001','email'=>'bichman230595@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'LÝ XUÂN HƯỚNG','employee_code'=>'4025','email'=>'xuanhuong2705@gmail.com','department'=>'Phòng QC'],
            ['name'=>'NGUYỄN THỊ HIỆP','employee_code'=>'4026','email'=>'Hiepnam2020@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'NGUYỄN THỊ PHỚI','employee_code'=>'4051','email'=>'phoivalananh1234@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'ĐẶNG THỊ LAN','employee_code'=>'4058','email'=>null,'department'=>'Phòng QC'],
            ['name'=>'TRẦN  THỊ BÍCH  THÂN','employee_code'=>'4062','email'=>'tranthibichthanvta@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'BÀNH XUÂN TRƯỞNG','employee_code'=>'4066','email'=>'tranxuan12350@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'TRỊNH THỊ HƯƠNG QUỲNH','employee_code'=>'4124','email'=>null,'department'=>'Xưởng sản xuất'],
            ['name'=>'TRẦN THỊ HOÀI TƠ','employee_code'=>'4160','email'=>'tranthihoaito.13011985@gmail.com','department'=>'Phòng QC'],
            ['name'=>'THỊ CHÀNH THU','employee_code'=>'4177','email'=>null,'department'=>'Xưởng sản xuất'],
            ['name'=>'NGUYỄN THỊ HỒNG GIANG','employee_code'=>'4184','email'=>'hg282863@gmail.com','department'=>'Phòng QC'],
            ['name'=>'NGÔ THỊ SẺ','employee_code'=>'4240','email'=>null,'department'=>'Phòng QC'],
            ['name'=>'PHẠM THỊ NGỌC CẨM','employee_code'=>'4276','email'=>null,'department'=>'Xưởng sản xuất'],
            ['name'=>'TRẦN THỊ KIM THE','employee_code'=>'4285','email'=>null,'department'=>'Xưởng sản xuất'],
            ['name'=>'NGUYỄN NGỌC HUYỀN','employee_code'=>'4291','email'=>null,'department'=>'Phòng QC'],
            ['name'=>'THỊ DỊU','employee_code'=>'4302','email'=>'thidiuviettel21@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'THÂN THỊ DUNG','employee_code'=>'4312','email'=>null,'department'=>'Xưởng sản xuất'],
            ['name'=>'LÊ THỊ HIỀN','employee_code'=>'4314','email'=>null,'department'=>'Xưởng sản xuất'],
            ['name'=>'TRẦN THỊ THỦY TIÊN','employee_code'=>'4321','email'=>null,'department'=>'Xưởng sản xuất'],
            ['name'=>'ĐINH THỊ TÚ LOAN','employee_code'=>'4338','email'=>null,'department'=>'Xưởng sản xuất'],
            ['name'=>'ĐÀO THỊ MỸ HIỀN','employee_code'=>'4344','email'=>'hiendao157@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'CAO THỊ VĨNH KIỀU','employee_code'=>'4364','email'=>'biagasthanhhung279333@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'LÊ THỊ OANH','employee_code'=>'4381','email'=>'lengocoanhv@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'CAO THỊ DIỄM THI','employee_code'=>'4408','email'=>null,'department'=>'Xưởng sản xuất'],
            ['name'=>'THI QUỐC HIỆP','employee_code'=>'4434','email'=>'hiepthiquoc1993@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'PHẠM THỊ TRANG','employee_code'=>'4440','email'=>'phamthitrangonamba@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'NGUYỄN THỊ LỆ QUYÊN','employee_code'=>'4446','email'=>'ngthilequyen96@icloud.com','department'=>'Xưởng sản xuất'],
            ['name'=>'HOÀNG ĐOÀN THỊ THƠ','employee_code'=>'4450','email'=>null,'department'=>'Xưởng sản xuất'],
            ['name'=>'TRẦN TẤN PHONG','employee_code'=>'4490','email'=>null,'department'=>'Ban Giám đốc'],
            ['name'=>'PHẠM VĨNH XUYÊN','employee_code'=>'4491','email'=>null,'department'=>'Phòng Kinh doanh'],
            ['name'=>'ĐÀO THỊ NGỌC MAI','employee_code'=>'4536','email'=>null,'department'=>'Phòng Nhân sự'],
            ['name'=>'VŨ CÔNG THẮNG','employee_code'=>'4549','email'=>'robin.thang19@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'NGUYỄN THỊ NGỌC YẾN','employee_code'=>'4553','email'=>null,'department'=>'Phòng QC'],
            ['name'=>'LÊ MINH TUẤN ANH ','employee_code'=>'4565','email'=>null,'department'=>'Phòng IT'],
            ['name'=>'NGUYỄN THỊ THƠM','employee_code'=>'4567','email'=>null,'department'=>'Phòng QC'],
            ['name'=>'LÊ THỊ YẾN NHI','employee_code'=>'4568','email'=>null,'department'=>'Phòng QC'],
            ['name'=>'NGUYỄN THỊ QUYÊN','employee_code'=>'4571','email'=>null,'department'=>'Phòng QC'],
            ['name'=>'NGUYỄN THỊ NGỌC HÀ','employee_code'=>'4585','email'=>'nguyenthingocha200492@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'NGUYỄN THỊ QUỲNH NHƯ','employee_code'=>'4587','email'=>'nhubuta300497@gmail.com','department'=>'Phòng QC'],
            ['name'=>'VÕ THỊ HÀ MY','employee_code'=>'4590','email'=>null,'department'=>'Phòng QC'],
            ['name'=>'VŨ THỊ NGOAN','employee_code'=>'4593','email'=>null,'department'=>'Phòng QC'],
            ['name'=>'VÕ THỊ HUỲNH NHƯ','employee_code'=>'4595','email'=>'vothihuynhnhu1007@gmail.com','department'=>'Phòng QC'],
            ['name'=>'NGUYỄN THỊ YẾN','employee_code'=>'4598','email'=>null,'department'=>'Xưởng sản xuất'],
            ['name'=>'PHAN THỊ DIỄM PHÚC ','employee_code'=>'4600','email'=>null,'department'=>'Xưởng sản xuất'],
            ['name'=>'TỪ THỊ THANH THỦY','employee_code'=>'4603','email'=>null,'department'=>'Xưởng sản xuất'],
            ['name'=>'HÀ THỊ PHƯƠNG MẪN','employee_code'=>'4605','email'=>'phuongman2412@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'TRẦN THỊ LIÊN','employee_code'=>'4614','email'=>null,'department'=>'Xưởng sản xuất'],
            ['name'=>'PHẠM THỊ THU THỦY','employee_code'=>'4621','email'=>'thuthuy3873@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'LÊ THỊ TOÀN','employee_code'=>'4631','email'=>null,'department'=>'Xưởng sản xuất'],
            ['name'=>'LÊ KHÁNH HUYỀN','employee_code'=>'4636','email'=>'lekhanhhuyen22091998@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'TRƯƠNG THỊ QUYÊN','employee_code'=>'4640','email'=>null,'department'=>'Xưởng sản xuất'],
            ['name'=>'CHÂU THỊ MỸ DUNG','employee_code'=>'4641','email'=>null,'department'=>'Xưởng sản xuất'],
            ['name'=>'NÔNG THỊ DUNG','employee_code'=>'4645','email'=>null,'department'=>'Xưởng sản xuất'],
            ['name'=>'TRẦN THỊ HỒNG ĐANG','employee_code'=>'4656','email'=>'tranthihongdan010193@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'LƯƠNG THỊ A TIÊN','employee_code'=>'4657','email'=>'luongtien28021992@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'PHẠM THỊ DIỂM MY','employee_code'=>'4662','email'=>null,'department'=>'Xưởng sản xuất'],
            ['name'=>'LA THỊ NHA','employee_code'=>'4664','email'=>null,'department'=>'Xưởng sản xuất'],
            ['name'=>'NGUYỄN THỊ MỸ DUYÊN','employee_code'=>'4665','email'=>null,'department'=>'Xưởng sản xuất'],
            ['name'=>'LÊ THỊ TUYẾT HẠNH','employee_code'=>'4675','email'=>null,'department'=>'Phòng QC'],
            ['name'=>'LỤC THỊ EM','employee_code'=>'4680','email'=>'Phuongem.94@icloud.com','department'=>'Xưởng sản xuất'],
            ['name'=>'HUỲNH THỊ HỒNG LAM','employee_code'=>'4684','email'=>'lamhuynh.190493@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'RMAH RU NÉT','employee_code'=>'4688','email'=>'rmahrynet1994@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'PHẠM THỊ YẾN','employee_code'=>'4705','email'=>null,'department'=>'Xưởng sản xuất'],
            ['name'=>'NGUYỄN THỊ DIỆP','employee_code'=>'4713','email'=>null,'department'=>'Ban Giám đốc'],
            ['name'=>'VÕ HOÀNG LIÊN','employee_code'=>'4714','email'=>null,'department'=>'Xưởng sản xuất'],
            ['name'=>'THỊ CHẠNH','employee_code'=>'4732','email'=>'thic3776@gmail.com','department'=>'Phòng IT'],
            ['name'=>'TRƯƠNG CÔNG BẰNG','employee_code'=>'4741','email'=>'truongcongbang@onamba.com.vn','department'=>'Ban Giám đốc'],
            ['name'=>'NGUYỄN THỊ NĂM','employee_code'=>'4743','email'=>null,'department'=>'Phòng QC'],
            ['name'=>'VI THỊ BÍCH THÊU','employee_code'=>'4750','email'=>null,'department'=>'Xưởng sản xuất'],
            ['name'=>'TRẦN NGỌC PHƯƠNG','employee_code'=>'4753','email'=>'ngocphuong.55918@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'TRẦN THỊ THẢO','employee_code'=>'4765','email'=>null,'department'=>'Xưởng sản xuất'],
            ['name'=>'NGUYỄN VĂN CƯỜNG ','employee_code'=>'4772','email'=>'cuongvan7782@gmail.com','department'=>'Phòng IT'],
            ['name'=>'TRẦN LAN HƯƠNG','employee_code'=>'4777','email'=>null,'department'=>'Phòng Nhân sự'],
            ['name'=>'ĐẶNG THỊ THÚY','employee_code'=>'4778','email'=>'thuy.khalinh@gmail.com','department'=>'Phòng IT'],
            ['name'=>'HUỲNH THỊ NGỌC HẠNH','employee_code'=>'4779','email'=>null,'department'=>'Phòng IT'],
            ['name'=>'TRƯƠNG ÁNH NGUYỆT','employee_code'=>'4816','email'=>null,'department'=>'Phòng QC'],
            ['name'=>'PHẠM KHÁNH LY','employee_code'=>'4818','email'=>'lylovely89@gmail.com','department'=>'Ban Giám đốc'],
            ['name'=>'NGUYỄN HUỲNH THANH THUẬT','employee_code'=>'4822','email'=>'nthuat752@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'NGUYỄN CÔNG LỢI','employee_code'=>'4824','email'=>'nguyencongloi9396@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'NGUYỄN THÀNH CÔNG','employee_code'=>'4826','email'=>null,'department'=>'Phòng IT'],
            ['name'=>'TRẦN THỊ NGỌC THƯ','employee_code'=>'4829','email'=>null,'department'=>'Xưởng sản xuất'],
            ['name'=>'HÀ THỊ THANH THỰC ','employee_code'=>'4831','email'=>'thanhthuc84@gmail.com','department'=>'Ban Giám đốc'],
            ['name'=>'VÕ XUÂN TRANG','employee_code'=>'4841','email'=>null,'department'=>'Xưởng sản xuất'],
            ['name'=>'LÂM THỊ KIM EM','employee_code'=>'4849','email'=>'Lamthikimem953@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'TRẦN THỊ NGỌC ÚT','employee_code'=>'4850','email'=>null,'department'=>'Xưởng sản xuất'],
            ['name'=>'NGUYỄN THỊ MỸ TIÊN','employee_code'=>'4863','email'=>'090700tien@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'PHẠM THÀNH DI','employee_code'=>'4868','email'=>'Phamthanhduy7788@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'TRỊNH THỊ MỸ SINH','employee_code'=>'4884','email'=>'sinhtrinh093@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'TRẦN NHÃ TUẤN','employee_code'=>'4910','email'=>'trantuan.050119@gmail.com','department'=>'Phòng QC'],
            ['name'=>'HỨA THỊ NHANH','employee_code'=>'4923','email'=>'huathinham18101984@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'NGUYỄN VĂN HOÀNG','employee_code'=>'4937','email'=>'ngthanhhoang707@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'NGUYỄN THỊ HOÀNG ANH','employee_code'=>'4944','email'=>null,'department'=>'Phòng QC'],
            ['name'=>'DANH VĂN HÊN','employee_code'=>'4951','email'=>null,'department'=>'Xưởng sản xuất'],
            ['name'=>'NGUYỄN THỊ THÚY KIỀU','employee_code'=>'4952','email'=>null,'department'=>'Xưởng sản xuất'],
            ['name'=>'NGUYỄN THỊ TRÚC PHƯƠNG ','employee_code'=>'4954','email'=>null,'department'=>'Xưởng sản xuất'],
            ['name'=>'NGUYỄN THỊ MỸ CHÂU','employee_code'=>'4960','email'=>null,'department'=>'Phòng IT'],
            ['name'=>'NGUYỄN THÀNH ĐƯỢC','employee_code'=>'4966','email'=>'nguyenthanhduoc4818@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'VÕ THỊ KIM OANH','employee_code'=>'4981','email'=>null,'department'=>'Ban Giám đốc'],
            ['name'=>'NGUYỄN THỊ THANH THẢO','employee_code'=>'4982','email'=>'thanhthao1703@gmail.com','department'=>'Phòng Kinh doanh'],
            ['name'=>'NGUYỄN THỊ KIM CHI','employee_code'=>'5011','email'=>null,'department'=>'Xưởng sản xuất'],
            ['name'=>'VÕ NGỌC QUYỀN','employee_code'=>'5015','email'=>null,'department'=>'Xưởng sản xuất'],
            ['name'=>'LÊ THỊ CẪM LOAN','employee_code'=>'5016','email'=>null,'department'=>'Phòng QC'],
            ['name'=>'NGUYỄN THỊ HỒNG','employee_code'=>'5018','email'=>null,'department'=>'Xưởng sản xuất'],
            ['name'=>'ĐỖ THỊ KIM TY','employee_code'=>'5071','email'=>null,'department'=>'Phòng Kinh doanh'],
            ['name'=>'VÕ THANH TUẤN','employee_code'=>'5077','email'=>null,'department'=>'Phòng QC'],
            ['name'=>'HOÀNG THỊ THANH','employee_code'=>'5081','email'=>null,'department'=>'Xưởng sản xuất'],
            ['name'=>'CAO HUỲNH THANH KIỀU','employee_code'=>'5099','email'=>'bemap130394@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'LÊ THỊ HUỲNH HOA ','employee_code'=>'5108','email'=>'lthhoa16nh@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'PHAN TRỌNG PHƯỚC','employee_code'=>'5109','email'=>'phantrongphuoc68@gmail.com','department'=>'Phòng Hành chính'],
            ['name'=>'NGUYỄN ANH KIỆT','employee_code'=>'5129','email'=>'kietnguyen512413@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'PHẠM ANH THƯ','employee_code'=>'5131','email'=>'pthu36701@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'VÕ PHAN KỲ DUYÊN','employee_code'=>'5136','email'=>'Kyduyen22072001@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'DANH THỊ KIỀU OANH','employee_code'=>'5137','email'=>'danhkieuoanh2@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'ĐOÀN MINH LAI','employee_code'=>'5145','email'=>'doanminhlai5157@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'TRẦN THỊ KHƯƠNG ANH','employee_code'=>'5148','email'=>'anhtran3879@gmail.com','department'=>'Phòng Logistics'],
            ['name'=>'TRẦN THỊ THANH HUYỀN','employee_code'=>'5156','email'=>null,'department'=>'Phòng Logistics'],
            ['name'=>'PHẠM THỊ HUYỀN','employee_code'=>'5157','email'=>'huyenpham3011.mtx@gmail.com','department'=>'Phòng Hành chính'],
            ['name'=>'BÙI THỊ HẰNG','employee_code'=>'5158','email'=>'buihangvhk31@gmail.com','department'=>'Ban Giám đốc'],
            ['name'=>'HUỲNH MỸ NGHI','employee_code'=>'5168','email'=>'Huynhnghi9796@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'NGUYỄN THỊ LÀI SƯƠNG','employee_code'=>'5176','email'=>'ssuong501@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'LÊ THỊ ÚT GẤM','employee_code'=>'5177','email'=>'lethiutgam99@icloud.com','department'=>'Xưởng sản xuất'],
            ['name'=>'NGUYỄN MINH HIỆU','employee_code'=>'5188','email'=>'nguyenminhhieu0386437317@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'LÊ THỊ NGỌC PHƯƠNG','employee_code'=>'5195','email'=>'lethingocphuong.hg@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'NGUYỄN THỊ TÂM','employee_code'=>'5199','email'=>'nguyentam11101985@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'VÕ THỊ HƯƠNG','employee_code'=>'5210','email'=>null,'department'=>'Xưởng sản xuất'],
            ['name'=>'TRỊNH HỒNG ĐOAN','employee_code'=>'5221','email'=>'doan19021998@icloud.com','department'=>'Xưởng sản xuất'],
            ['name'=>'BÙI THỊ VÂN','employee_code'=>'5223','email'=>'vquoc2830@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'TRỊNH THỊ TRÚC','employee_code'=>'5240','email'=>'Trinhthitruc1108@gmail.com','department'=>'Phòng Hành chính'],
            ['name'=>'VI THỊ THƯƠNG','employee_code'=>'5248','email'=>'trungthuong48d@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'LÊ THỊ TUYẾT NGÂN','employee_code'=>'5249','email'=>null,'department'=>'Xưởng sản xuất'],
            ['name'=>'NGÔ ĐÌNH TUYÊN','employee_code'=>'5251','email'=>null,'department'=>'Xưởng sản xuất'],
            ['name'=>'PHẠM THỊ BÉ MỸ','employee_code'=>'5256','email'=>'phamthibemy7650@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'HỨA THỊ MỸ HOA','employee_code'=>'5265','email'=>'myhoa17031996@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'DƯƠNG THỊ NGỌC TRÂM','employee_code'=>'5268','email'=>'duongthingoctram1998@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'TÔ THI MAI','employee_code'=>'5273','email'=>null,'department'=>'Phòng QC'],
            ['name'=>'VY THỊ HUỀ','employee_code'=>'5276','email'=>'vyhue1404@icloud.com','department'=>'Xưởng sản xuất'],
            ['name'=>'NGUYỄN BẢO KIM NGÂN','employee_code'=>'5285','email'=>null,'department'=>'Phòng Kinh doanh'],
            ['name'=>'HỒ THỊ LAM','employee_code'=>'5296','email'=>'lamho7169@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'HỒ THANH PHƯỢNG','employee_code'=>'5300','email'=>null,'department'=>'Xưởng sản xuất'],
            ['name'=>'DANH BỒ NA','employee_code'=>'5302','email'=>null,'department'=>'Xưởng sản xuất'],
            ['name'=>'NGUYỄN THỊ PHƯƠNG','employee_code'=>'5304','email'=>'nguyenthiphuonght@gmail.com','department'=>'Phòng Nhân sự'],
            ['name'=>'HỒ THỊ MỸ','employee_code'=>'5310','email'=>'homy041188@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'NGUYỄN THỊ MỸ TIÊN','employee_code'=>'5318','email'=>'ngthimytien57@icloud.com','department'=>'Xưởng sản xuất'],
            ['name'=>'NGUYỄN THỊ THÚY ANH','employee_code'=>'5324','email'=>'heongok141195@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'TRỊNH THỊ MỸ NGỌC ','employee_code'=>'5345','email'=>null,'department'=>'Xưởng sản xuất'],
            ['name'=>'NGUYỄN TRIỆU THANH PHÚC','employee_code'=>'5348','email'=>'nguyenphuc4040@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'NGUYỄN THỊ HỒNG HẬU','employee_code'=>'5355','email'=>'nguyenthihonghau62@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'NGUYỄN HUỲNH KHANG','employee_code'=>'5358','email'=>'nguyenhuynhkhang01091996@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'LÂM THỊ KIM NGUYÊN','employee_code'=>'5367','email'=>'nguyen29022001@icloud.com','department'=>'Xưởng sản xuất'],
            ['name'=>'LÊ THỊ DIỄM TRINH','employee_code'=>'5374','email'=>'lethidiemtrinh278@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'NGUYỄN VĂN NGỘ','employee_code'=>'5382','email'=>'nguyenngo488@icloud.com','department'=>'Xưởng sản xuất'],
            ['name'=>'PHẠM NGỌC KHA','employee_code'=>'5389','email'=>null,'department'=>'Xưởng sản xuất'],
            ['name'=>'NGUYỄN THỊ CẨM TÚ','employee_code'=>'5406','email'=>'Camtu08051999@icloud.com','department'=>'Xưởng sản xuất'],
            ['name'=>'LĂNG THỊ VÂN ','employee_code'=>'5407','email'=>'langvan1503@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'LĂNG THỊ HẢI YẾN','employee_code'=>'5408','email'=>'Yenlangthihai@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'TRẦN VĂN HỮU','employee_code'=>'5409','email'=>'trannhuuu000@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'LÊ THỊ THU DUNG','employee_code'=>'5410','email'=>'5410.thudung.vto@gmail.com','department'=>'Phòng Kế toán'],
            ['name'=>'HOÀNG THỊ THANH NỮ THỦY TIÊN','employee_code'=>'5415','email'=>null,'department'=>'Xưởng sản xuất'],
            ['name'=>'VÕ THỊ BÍCH LIÊN','employee_code'=>'5421','email'=>null,'department'=>'Xưởng sản xuất'],
            ['name'=>'PHAN THỊ HỒNG YẾN','employee_code'=>'5422','email'=>'hongyenphan94@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'HUỲNH THỊ MỸ DUYÊN','employee_code'=>'5427','email'=>'htmd5518@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'HOÀNG MINH HẢI','employee_code'=>'5437','email'=>'hoangminhhai2650@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'NGUYỄN THỊ ÁNH','employee_code'=>'5439','email'=>'nguyenthianh1986thianh@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'VÕ THÚY KIỀU','employee_code'=>'5440','email'=>'kt3539709@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'TRẦN THỊ MỸ HẠ','employee_code'=>'5450','email'=>'tranthimyha2050@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'VÕ THỊ XUYẾN','employee_code'=>'5452','email'=>null,'department'=>'Xưởng sản xuất'],
            ['name'=>'HỒ THỊ KIM THI','employee_code'=>'5469','email'=>'hokimthi42@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'TĂNG THỊ SÔ RI GIA','employee_code'=>'5479','email'=>'rigiatangthi@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'LÊ QUỐC KIỆT','employee_code'=>'5491','email'=>'lekietmhd123@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'GIANG THANH TÂN','employee_code'=>'5501','email'=>'Giangthithi35xz@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'NGUYỄN THỊ CẨM LINH','employee_code'=>'5505','email'=>'ncamlinh445@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'BÙI XUÂN QUỐC','employee_code'=>'5508','email'=>null,'department'=>'Xưởng sản xuất'],
            ['name'=>'NGUYỄN THANH QUANG','employee_code'=>'5510','email'=>'nguyenthanhquang5064@gmail.com','department'=>'Phòng IT'],
            ['name'=>'NGUYỄN THỊ THU THẢO','employee_code'=>'5517','email'=>'thuthao110399@gmail.com','department'=>'Phòng IT'],
            ['name'=>'NGUYỄN NGỌC THI','employee_code'=>'5527','email'=>'naulun1994@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'ĐỖ LÊ THANH TUYỀN','employee_code'=>'5544','email'=>'dolethanhtuyen.1996@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'LÂM KIM NHIÊN','employee_code'=>'5551','email'=>'Lamkimnhien26071996@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'ĐỖ VĂN HẢO','employee_code'=>'5563','email'=>'haodo297@gmail.com','department'=>'Ban Giám đốc'],
            ['name'=>'TRỊNH THỊ HÀ','employee_code'=>'5564','email'=>'hatrinh496@gmail.com','department'=>'Ban Giám đốc'],
            ['name'=>'LÊ THỊ NHU MỸ','employee_code'=>'5573','email'=>'myctag5161@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'LÊ THỊ TÀI','employee_code'=>'5578','email'=>null,'department'=>'Xưởng sản xuất'],
            ['name'=>'NGUYỄN THU THƯƠNG','employee_code'=>'5579','email'=>null,'department'=>'Xưởng sản xuất'],
            ['name'=>'LƯƠNG THỊ HỒNG NHUNG','employee_code'=>'5581','email'=>'luonghongnhung0103@gmail.com','department'=>'Phòng Logistics'],
            ['name'=>'NGUYỄN THỊ KIM NGỌC','employee_code'=>'5583','email'=>null,'department'=>'Xưởng sản xuất'],
            ['name'=>'ĐOÀN THỊ NHƯ Ý','employee_code'=>'5584','email'=>null,'department'=>'Xưởng sản xuất'],
            ['name'=>'HỜ THƠM','employee_code'=>'5589','email'=>'hothom12061998@icloud.com','department'=>'Xưởng sản xuất'],
            ['name'=>'SƠN THỊ HIỀN','employee_code'=>'5592','email'=>'Sonqui678@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'PHẠM Y PHỤNG','employee_code'=>'5599','email'=>'phamyphung02@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'NGUYỄN THỊ KIM HUYỀN','employee_code'=>'5614','email'=>null,'department'=>'Xưởng sản xuất'],
            ['name'=>'NGUYỄN VĂN KIÊN','employee_code'=>'5632','email'=>null,'department'=>'Xưởng sản xuất'],
            ['name'=>'NGUYỄN THỊ NGHIÊN','employee_code'=>'5645','email'=>'nguyennghien194@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'NGUYỄN VĂN TÂM','employee_code'=>'5654','email'=>null,'department'=>'Xưởng sản xuất'],
            ['name'=>'LÊ THỊ MỸ LỆ HẰNG','employee_code'=>'5685','email'=>'lehang.200919@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'QUÁCH MỘNG MỸ TUYỀN','employee_code'=>'5693','email'=>'mytuyen02081996@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'HỨA THỊ MỸ TRANG','employee_code'=>'5700','email'=>'trang080404@icloud.com','department'=>'Xưởng sản xuất'],
            ['name'=>'NGŨ PHƯỚC HIỆP','employee_code'=>'5701','email'=>'nguphuochiep13102001@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'PHÙNG THỊ LỆ THU','employee_code'=>'5706','email'=>null,'department'=>'Phòng QC'],
            ['name'=>'ĐINH VĂN LƯU','employee_code'=>'5707','email'=>null,'department'=>'Phòng QC'],
            ['name'=>'PHAN NGỌC LINH','employee_code'=>'5708','email'=>null,'department'=>'Xưởng sản xuất'],
            ['name'=>'NGUYỄN VĂN QUÂN','employee_code'=>'5720','email'=>null,'department'=>'Phòng Nhân sự'],
            ['name'=>'TRẦN THỊ NGỌC PHƯƠNG','employee_code'=>'5726','email'=>null,'department'=>'Xưởng sản xuất'],
            ['name'=>'DANH LƯU HỒNG THƯ','employee_code'=>'5729','email'=>'hongthu200212@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'LÊ THỊ CẨM NANG','employee_code'=>'5730','email'=>'Lethicamnang0948@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'TRẦN THỊ KIM TIẾN','employee_code'=>'5750','email'=>'tieniachay2@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'LÝ THỊ HIỆP','employee_code'=>'5756','email'=>'lythihiep2025@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'THỊ XINH','employee_code'=>'5767','email'=>'thixinh01072001@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'NGUYỄN THỊ ÁI TRÂN','employee_code'=>'5770','email'=>'tgiabiin@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'NGUYỄN THỊ NGỌC','employee_code'=>'5777','email'=>'ngocnguyen24021997@gmail.com','department'=>'Phòng Logistics'],
            ['name'=>'THỊ NGỌC DÀNH','employee_code'=>'5779','email'=>'thingocchanh311@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'NGUYỄN THỊ THÙY TRANG','employee_code'=>'5780','email'=>'thuytrang011097p@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'NGUYỄN NGỌC HÂN','employee_code'=>'5783','email'=>'jybiken@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'HỒ THỊ NGỌC GIÀU','employee_code'=>'5785','email'=>'hothingocgiau94@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'NGUYỄN THỊ LƯƠNG','employee_code'=>'5790','email'=>'ln8670154@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'DƯƠNG THỦY TIÊN','employee_code'=>'5791','email'=>'tienduong41052@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'VI THỊ LY NA','employee_code'=>'5792','email'=>'Vithilyna2297@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'DANH THỊ MỸ HƯƠNG','employee_code'=>'5799','email'=>'Tranvuphuong4658@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'HÀNG NGỌC ĐỂ','employee_code'=>'5805','email'=>null,'department'=>'Xưởng sản xuất'],
            ['name'=>'MAI THỊ MỸ DUNG','employee_code'=>'5807','email'=>null,'department'=>'Xưởng sản xuất'],
            ['name'=>'NGUYỄN THỊ THÂU NGÂN','employee_code'=>'5830','email'=>'nguyenngan348@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'VŨ NGỌC MINH CHÂU','employee_code'=>'5832','email'=>'vnmcbd@gmail.com','department'=>'Phòng Hành chính'],
            ['name'=>'TRẦN THỊ HỒNG XUYẾN ','employee_code'=>'5833','email'=>'hongxuyen666161@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'TRẦN THỊ KIM THOA','employee_code'=>'5841','email'=>'tranthoa1291998@gmail.com','department'=>'Phòng QC'],
            ['name'=>'HỜ YÊN','employee_code'=>'5855','email'=>'mochi0522002@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'NGUYỄN THỊ Bão YẾN','employee_code'=>'5875','email'=>'Nguyenthibaoyenyen37@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'NGUYỄN KHẮC DƯƠNG','employee_code'=>'5878','email'=>'duongkhac656@gmail.com','department'=>'Phòng IT'],
            ['name'=>'NGUYỄN THỊ LUÂN','employee_code'=>'5882','email'=>null,'department'=>'Xưởng sản xuất'],
            ['name'=>'NGUYỄN DIỄM TRINH','employee_code'=>'5900','email'=>'nguyendiemtrinh12081995@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'NGUYỄN XUÂN HUYỀN','employee_code'=>'5908','email'=>'xuanhuyen10061998@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'THẠCH THỊ SA KHONE','employee_code'=>'5912','email'=>'thachthisakhone685@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'SƠN THỊ THANH NGÂN','employee_code'=>'5915','email'=>'sonthanhngan54@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'LÊ THỊ GIÀU','employee_code'=>'5916','email'=>'levantinhdmxgr@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'LA NGỌC PHƯỢNG','employee_code'=>'5917','email'=>'ngocphuongla1994@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'TRẦN THỊ DIỄM KIỀU','employee_code'=>'5919','email'=>'trankieu260492@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'NGUYỄN CẨM TIÊN','employee_code'=>'5932','email'=>'nguyencamtien0807@icloud.com','department'=>'Xưởng sản xuất'],
            ['name'=>'TRƯƠNG THỊ MỸ TRINH','employee_code'=>'5940','email'=>null,'department'=>'Xưởng sản xuất'],
            ['name'=>'TRẦN VĂN KHÔI','employee_code'=>'5943','email'=>'tranvankhoi2K@gmail.com','department'=>'Phòng IT'],
            ['name'=>'NGUYỄN THỊ KIM CHI','employee_code'=>'5952','email'=>'kimchivanphuc301022@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'LÝ VĂN PHÚC','employee_code'=>'5953','email'=>'hoangphuc.299.000@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'TĂNG NGỌC HUYỀN','employee_code'=>'5955','email'=>'huyentangngoc2@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'NGUYỄN THỊ MAI QUYÊN','employee_code'=>'5959','email'=>'maiquyen14111999@icloud.com','department'=>'Xưởng sản xuất'],
            ['name'=>'KIM THỊ THU TRANG','employee_code'=>'5961','email'=>'kim755648@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'NGUYỄN THỊ TƯƠI','employee_code'=>'5971','email'=>'nguyenminhdang20131007@gmail.com','department'=>'Phòng QC'],
            ['name'=>'THỊ NGÂN','employee_code'=>'5975','email'=>'nganthi.200500@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'LÊ THỊ ANH THƯ','employee_code'=>'5980','email'=>'lethianhthu1319@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'TRẦN BÉ NIỀM','employee_code'=>'5992','email'=>'beniem0409@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'TRẦN THỊ THU TRANG','employee_code'=>'5996','email'=>'phanthanhhoai12292@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'NGUYỄN THỊ MỸ XIÊNG','employee_code'=>'6006','email'=>'nguyenthimyxuyen313@icloud.com','department'=>'Phòng IT'],
            ['name'=>'LÊ THỊ BÍCH NHI','employee_code'=>'6016','email'=>null,'department'=>'Phòng IT'],
            ['name'=>'HUỲNH THỊ HẠNH','employee_code'=>'6017','email'=>null,'department'=>'Phòng IT'],
            ['name'=>'NGUYỄN THỊ THU THẢO','employee_code'=>'6022','email'=>'nguyenthithuthao6022@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'HÀ THANH HOÀI','employee_code'=>'6024','email'=>null,'department'=>'Xưởng sản xuất'],
            ['name'=>'TRƯƠNG THỊ NGỌC NHU','employee_code'=>'6035','email'=>'llngocnhu1998@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'LÊ KIM SÁNH','employee_code'=>'6036','email'=>'lekimsanhbd14@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'THỊ KIM PHỤNG','employee_code'=>'6041','email'=>'thikimphung12613@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'NGUYỄN THỊ BÍCH TUYỀN','employee_code'=>'6042','email'=>'nguyenthibichtuyen2207@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'NGUYỄN THỊ THÙY LINH','employee_code'=>'6050','email'=>'thuylinh@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'TRẦN THỊ THẢO','employee_code'=>'6052','email'=>'tthaoootraan@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'NGUYỄN THỊ KIM NGÂN','employee_code'=>'6053','email'=>'ngan212290@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'ĐẶNG THỊ VẸN','employee_code'=>'6064','email'=>'dangthiven1839@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'TRẦN VŨ LINH ','employee_code'=>'6073','email'=>null,'department'=>'Phòng QC'],
            ['name'=>'TRIỆU MỘNG THÙY TRINH','employee_code'=>'6084','email'=>'trieumongthuytrinh@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'TÔ THỊ THƯ','employee_code'=>'6089','email'=>'tothu909420@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'THẠCH THỊ CHAN MA LY','employee_code'=>'6090','email'=>'tinadonxuan305@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'KIM THỊ SA MẾTE','employee_code'=>'6091','email'=>'Kimthisamete@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'CAO THỊ DIỆU','employee_code'=>'6092','email'=>'caodieubd1988@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'LÊ HỒNG DÂN','employee_code'=>'6095','email'=>'hongdan2001tv@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'NGUYỄN THỊ YẾN NHI','employee_code'=>'6109','email'=>null,'department'=>'Xưởng sản xuất'],
            ['name'=>'KIM THỊ THU TRINH','employee_code'=>'6115','email'=>'kimthithutrinh1997@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'KIM THỊ LÂY','employee_code'=>'6122','email'=>'kimthilay230592@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'NGUYỄN THỦY TIÊN','employee_code'=>'6125','email'=>'nguyenthuytien24101997@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'TRẦN BÍCH THỦY','employee_code'=>'6126','email'=>'bichthuy20022002@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'HUỲNH THỊ NHÀN','employee_code'=>'6131','email'=>'nhan120892@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'HÀ THỊ ÁNH','employee_code'=>'6134','email'=>null,'department'=>'Xưởng sản xuất'],
            ['name'=>'NGUYỄN THỊ LÀNH','employee_code'=>'6135','email'=>'nguyenthilanh14071990@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'NGUYỄN THỊ TUYẾT NHI','employee_code'=>'6150','email'=>'nguyenthituyetnhi744@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'LÊ TRƯƠNG TRÂM ANH','employee_code'=>'6155','email'=>'tanh888777@gmail.com','department'=>'Phòng QC'],
            ['name'=>'NGUYỄN BÍCH TRÂM','employee_code'=>'6160','email'=>'tramn1774@gmail.com','department'=>'Phòng QC'],
            ['name'=>'LÂM THỊ KIM NGÂN','employee_code'=>'6161','email'=>'lamnganngoc1096@gmail.com','department'=>'Phòng QC'],
            ['name'=>'NGÔ THÚY QUYÊN','employee_code'=>'6168','email'=>'thuyquyen4556@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'TRỊNH KIỀU PHIL','employee_code'=>'6169','email'=>'trinhphil95@gmail.com','department'=>'Phòng Nhân sự'],
            ['name'=>'PHAN THỊ MỸ LINH','employee_code'=>'6172','email'=>'phanthimylinh6172@gmail.com','department'=>'Phòng IT'],
            ['name'=>'PHẠM THỊ THẢO LY','employee_code'=>'6179','email'=>'thaoly9942@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'NGUYỄN THỊ XUÂN ','employee_code'=>'6184','email'=>'Nguyenxuand39@gmail.com','department'=>'Phòng QC'],
            ['name'=>'TRẦN THỊ KHÁNH LINH','employee_code'=>'6186','email'=>'khanhlinh03021999@gmail.com','department'=>'Phòng Kế toán'],
            ['name'=>'HỒ THANH SANG','employee_code'=>'6187','email'=>null,'department'=>'Phòng IT'],
            ['name'=>'NGUYỄN THÀNH SƠN','employee_code'=>'6189','email'=>'nguyenson.tvbds@gmail.com','department'=>'Phòng IT'],
            ['name'=>'NEÁNG SRÂY MÔM','employee_code'=>'6190','email'=>'neangsraymom6190@gmail.com','department'=>'Phòng IT'],
            ['name'=>'NGUYỄN THỊ THÙY DƯƠNG','employee_code'=>'6194','email'=>'duong030690@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'PHẠM THỊ ANH THƯ','employee_code'=>'6196','email'=>null,'department'=>'Xưởng sản xuất'],
            ['name'=>'KIM THỊ YẾN','employee_code'=>'6197','email'=>'kimthiyenpro9999@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'TRẦN THỊ KIM THU','employee_code'=>'6198','email'=>'thikimthutran.2106@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'HUỲNH THỊ HUỲNH NY','employee_code'=>'6199','email'=>'huynhny121118@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'HUỲNH VĂN TRUNG','employee_code'=>'6200','email'=>'trunghuynh01012003@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'HUỲNH THỊ HUỲNH NHƯ','employee_code'=>'6202','email'=>'huynhthihuynhnhu3496@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'PHAN NGỌC THƯ','employee_code'=>'6203','email'=>'phanngocthu09112004@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'VÕ THỊ TRÚC LY','employee_code'=>'6206','email'=>'votrucly2030@gmail.com','department'=>'Phòng IT'],
            ['name'=>'LƯƠNG THỊ KIM DUYÊN','employee_code'=>'6212','email'=>'Luongthikimduyen1989@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'BÙI THỊ MỸ LIÊN','employee_code'=>'6220','email'=>'mylien29112020@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'LONG THỊ NGÃ','employee_code'=>'6224','email'=>'longnga0505@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'LONG THỊ DÈO','employee_code'=>'6229','email'=>'longthaomai2000@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'NGUYỄN THỊ NGỌC QUYỀN','employee_code'=>'6233','email'=>'nguyenthingocquyenkg2025@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'NGUYỄN THÚY HẰNG','employee_code'=>'6235','email'=>'hangcamaunguyen@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'Y LUYẾN','employee_code'=>'6238','email'=>null,'department'=>'Xưởng sản xuất'],
            ['name'=>'LƯƠNG THỊ CẨM TIÊN','employee_code'=>'6239','email'=>'camtienluongthi5@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'LÊ DIỄM HƯƠNG NHI','employee_code'=>'6250','email'=>null,'department'=>'Xưởng sản xuất'],
            ['name'=>'THẠCH THỊ KIM NGÂN','employee_code'=>'6251','email'=>null,'department'=>'Xưởng sản xuất'],
            ['name'=>'SƠN THỊ HUỲNH NHƯ','employee_code'=>'6252','email'=>'Sonthihuynhnhutcvn@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'MAI THỊ KIM PHA','employee_code'=>'6253','email'=>'kimphabd30@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'QUÁCH THỊ CẨM TIÊN','employee_code'=>'6255','email'=>'tien52140@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'Y XEN','employee_code'=>'6258','email'=>'yxen2308kt@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'PHAN THỊ PHƯƠNG RI','employee_code'=>'6262','email'=>'phanphuongri4027@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'VÕ THỊ DIỄM MY','employee_code'=>'6264','email'=>'vodiemmy15061992@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'NGUYỄN NGỌC QUYỀN','employee_code'=>'6270','email'=>'zunkute2003@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'ĐÀO TRẦN ANH TÀI','employee_code'=>'6271','email'=>'daotai77777@icloud.com','department'=>'Phòng QC'],
            ['name'=>'PHẠM THỊ ĐÌNH','employee_code'=>'6272','email'=>'phamthidinh3411@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'VÕ THỊ THÙY LINH','employee_code'=>'6273','email'=>'linhvo7205@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'LÊ THỊ NGÂN','employee_code'=>'6275','email'=>'lethingan02069800@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'LƯƠNG THỊ THU HIỀN','employee_code'=>'6284','email'=>'hienluong110790@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'NGUYỄN HUỲNH DUY','employee_code'=>'6288','email'=>'nguyenhuynhduy2020.st@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'VÕ XUÂN NHẬT BÌNH','employee_code'=>'6299','email'=>'voxuannhatbinh@gmail.com','department'=>'Phòng Kinh doanh'],
            ['name'=>'KIM ĐẶNG HỒNG LOAN','employee_code'=>'6300','email'=>null,'department'=>'Xưởng sản xuất'],
            ['name'=>'QUAN THỊ THOA','employee_code'=>'6303','email'=>'quanthoa1201@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'LÝ HOÀNG NGÂN ','employee_code'=>'6304','email'=>'lyhona2107@gmail.com','department'=>'Phòng IT'],
            ['name'=>'LÊ THỊ TRÚC LY','employee_code'=>'6306','email'=>null,'department'=>'Xưởng sản xuất'],
            ['name'=>'TRẦN ANH ĐÀO ','employee_code'=>'6309','email'=>null,'department'=>'Xưởng sản xuất'],
            ['name'=>'PHẠM THANH BÌNH ','employee_code'=>'6314','email'=>'phambinh.oto.hui@gmail.com','department'=>'Phòng IT'],
            ['name'=>'NGUYỄN THỊ MAI LINH','employee_code'=>'6318','email'=>'nguyenthimailinh23112001@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'PHẠM THỊ YẾN NHI','employee_code'=>'6319','email'=>'phamthiyennhi27122005@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'TRẦN THÚY HẰNG','employee_code'=>'6320','email'=>'ht0847920@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'NGUYỄN THỊ NHI','employee_code'=>'6323','email'=>'nhin26711@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'LIỄU THỊ THU THANH ','employee_code'=>'6324','email'=>null,'department'=>'Phòng QC'],
            ['name'=>'NGUYỄN THỊ NGỌC TUYẾT','employee_code'=>'6325','email'=>'ntntuyet067@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'TRẦN THỊ MỸ CHI','employee_code'=>'6327','email'=>'Tranthimychi1357@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'TRẦN THỊ TRÚC MAI','employee_code'=>'6330','email'=>'tranthitrucmaitgdd2005@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'DANH THỊ HỒNG CẨM','employee_code'=>'6331','email'=>'Camdanh78@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'NGUYỄN VĂN TUẤN','employee_code'=>'6337','email'=>null,'department'=>'Xưởng sản xuất'],
            ['name'=>'NGUYỄN VĂN PHƯỜNG','employee_code'=>'6338','email'=>null,'department'=>'Xưởng sản xuất'],
            ['name'=>'LƯU THỊ HOA','employee_code'=>'6344','email'=>'Luu68563@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'HUỲNH TUYẾT NHI','employee_code'=>'6345','email'=>'huynhtuyetnhi2709@icloud.com','department'=>'Xưởng sản xuất'],
            ['name'=>'LÊ NGỌC KHA','employee_code'=>'6346','email'=>'lengockhaebigpro@icloud.com','department'=>'Xưởng sản xuất'],
            ['name'=>'TRẦN BÙI HẢI NHUNG','employee_code'=>'6350','email'=>'tranbuihainhung6350334@gmail.com','department'=>'Phòng Kế toán'],
            ['name'=>'NGUYỄN THỊ DIỆU HẰNG','employee_code'=>'6351','email'=>'hnguyen241193@gmail.com','department'=>'Phòng QC'],
            ['name'=>'PHAN HOÀNG THỤC TRINH','employee_code'=>'6354','email'=>null,'department'=>'Xưởng sản xuất'],
            ['name'=>'LÊ THANH TRÚC','employee_code'=>'6361','email'=>'lethanhtruc112002@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'ĐÀM THỊ QUỲNH NHƯ','employee_code'=>'6366','email'=>'damvanbinh961@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'NGUYỄN THỊ QUẾ TRÂN','employee_code'=>'6369','email'=>'tn2107564@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'NGUYỄN THÚY NGÀ','employee_code'=>'6370','email'=>'Ngaa67890@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'TRẦN MINH VƯƠNG EM','employee_code'=>'6371','email'=>'vuongtran17112021@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'LÊ THỊ NHƯ','employee_code'=>'6378','email'=>'huynhnhule520@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'HUỲNH THỊ YẾN NHI ','employee_code'=>'6394','email'=>'vto-logistics3@onamba.com.vn','department'=>'Phòng Logistics'],
            ['name'=>'THẠCH THỊ THU THẢO','employee_code'=>'6397','email'=>'thachthuthao2001tv@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'TRANG THỊ TRANG','employee_code'=>'6398','email'=>'thitrang1003@icloud.com','department'=>'Xưởng sản xuất'],
            ['name'=>'Y THỊ','employee_code'=>'6403','email'=>null,'department'=>'Xưởng sản xuất'],
            ['name'=>'TĂNG MỸ LINH','employee_code'=>'6404','email'=>'lunatatsuki169@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'ĐẶNG VIỆT HÙNG','employee_code'=>'6406','email'=>'dangh2188@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'NGUYỄN THỊ GẤM','employee_code'=>'6408','email'=>null,'department'=>'Xưởng sản xuất'],
            ['name'=>'NGUYỄN THỊ MỸ TIÊN','employee_code'=>'6409','email'=>null,'department'=>'Xưởng sản xuất'],
            ['name'=>'ĐỖ THỊ BÍCH TRÂM','employee_code'=>'6413','email'=>'dothibichtram14032022@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'CHÂU THỊ NHƯ Ý ','employee_code'=>'6416','email'=>null,'department'=>'Phòng QC'],
            ['name'=>'TRẦN MỸ PHƯỢNG ','employee_code'=>'6428','email'=>'tranmyphuong.fpt504@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'DƯƠNG THỊ NGỌC TRINH','employee_code'=>'6437','email'=>'duongthingoctrinh998@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'MAI KIỀU LAM','employee_code'=>'6440','email'=>'maikieulam123@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'HỒ THỊ KIM YẾN','employee_code'=>'6442','email'=>'hothikimyen519@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'LÊ THỊ THANH TÂM ','employee_code'=>'6453','email'=>'lethithanhtam2807@gmail.com','department'=>'Phòng IT'],
            ['name'=>'LÊ THỊ ANH THƯ','employee_code'=>'6458','email'=>'anhthu31501@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'NGÔ YẾN NHI ','employee_code'=>'6463','email'=>'yennhi1507ag@icloud.com','department'=>'Phòng QC'],
            ['name'=>'PHÙNG THỊ HUYỀN','employee_code'=>'6464','email'=>'phungthihuyen175@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'NÔNG THỊ BÍCH PHƯỢNG','employee_code'=>'6468','email'=>null,'department'=>'Xưởng sản xuất'],
            ['name'=>'PHẠM THỊ NGỌC CHẮC','employee_code'=>'6473','email'=>'ngocchac760@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'LÊ THỊ THANH NGA','employee_code'=>'6475','email'=>'lethithanhnga260186@gmail.com','department'=>'Phòng Logistics'],
            ['name'=>'PHẠM THỊ KIM THOA','employee_code'=>'6478','email'=>'phamthikimthoa0508@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'NGUYỄN THỊ HỒNG PHƯỢNG','employee_code'=>'6481','email'=>'phuonghongjapan39@gmail.com','department'=>'Phòng Nhân sự'],
            ['name'=>'NGUYỄN THỊ DIỆU HƯƠNG ','employee_code'=>'6483','email'=>'dieuhuongcute1408@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'BÙI THỊ YẾN VÂN','employee_code'=>'6487','email'=>'Yenv34996@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'TRẦN MINH NGUYÊN','employee_code'=>'6511','email'=>'minhnguyen231@gmail.com','department'=>'Phòng Logistics'],
            ['name'=>'VŨ THANH TUYỀN','employee_code'=>'6519','email'=>null,'department'=>'Xưởng sản xuất'],
            ['name'=>'THẠCH THỊ BÍCH ANH','employee_code'=>'6521','email'=>'thachthibichanh@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'TRẦN THỊ HƯƠNG','employee_code'=>'6523','email'=>'Chuminhchien0807@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'LÊ HỮU ĐỨC','employee_code'=>'6528','email'=>null,'department'=>'Xưởng sản xuất'],
            ['name'=>'QUÁCH MINH HOÀNG','employee_code'=>'6533','email'=>'quachminhhoang3297@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'KIỀU PHÚ QÚI','employee_code'=>'6537','email'=>'ggnews987@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'NGUYỄN VĂN NGHỈNH','employee_code'=>'6539','email'=>'nghinhnguyen144@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'NGUYỄN THỊ LÝ','employee_code'=>'6544','email'=>'nl051090@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'HUỲNH THỊ THANH NGÂN','employee_code'=>'6550','email'=>'huynhthithanhnganmx2022@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'TRẦN THỊ THU HIỀN','employee_code'=>'6558','email'=>'munchanh22061997@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'NGUYỄN VĂN TUẤN ','employee_code'=>'6565','email'=>'nvt23723@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'LÊ THỊ THÚY HUỲNH','employee_code'=>'6567','email'=>'lethithuyhuynh210120@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'THẠCH THỊ THANH LOAN','employee_code'=>'6568','email'=>'vnkhach57@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'TRẦN THÚY DUY','employee_code'=>'6570','email'=>'tranthuyduy2808@icloud.com','department'=>'Xưởng sản xuất'],
            ['name'=>'HUỲNH THỊ THÙY TRANG','employee_code'=>'6574','email'=>'huynhthithuytrang8846@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'TÔN NỮ TRÀ MY','employee_code'=>'6581','email'=>'topeheo@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'THỊ NGỌC LINH','employee_code'=>'6595','email'=>'ngoclinh1511203@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'MAI THANH THẢO','employee_code'=>'6604','email'=>null,'department'=>'Xưởng sản xuất'],
            ['name'=>'BÙI THỊ BÍCH NGỌC','employee_code'=>'6608','email'=>'phamthaonhi12300@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'ĐOÀN THỊ BÍCH NGÂN ','employee_code'=>'6609','email'=>'bichngandoan@icloud.com','department'=>'Xưởng sản xuất'],
            ['name'=>'NGUYỄN THỊ THÙY DƯƠNG','employee_code'=>'6611','email'=>'thuyduong.3062k2@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'HÀ THỊ KIỀU LINH','employee_code'=>'6613','email'=>'kieulinh300998@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'TRẦN HUỲNH CHƯƠNG','employee_code'=>'6614','email'=>'chuongnhi46@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'HÀ THỊ NHƯ BÌNH','employee_code'=>'6617','email'=>'nhubinh1314@gmail.com','department'=>'Phòng QC'],
            ['name'=>'NGÔ BÌNH PHƯỚC ','employee_code'=>'6618','email'=>'binhphuocngo143@gmail.com','department'=>'Phòng Logistics'],
            ['name'=>'NGUYỄN THÁI BÌNH','employee_code'=>'6625','email'=>null,'department'=>'Xưởng sản xuất'],
            ['name'=>'PHẠM VÕ HẢI ĐĂNG','employee_code'=>'6629','email'=>'dangpham1991@gmail.com','department'=>'Phòng Logistics'],
            ['name'=>'VÕ THỊ HỒNG NHIÊN','employee_code'=>'6631','email'=>'hongnhien191988@gmail.com','department'=>'Phòng QC'],
            ['name'=>'NGUYỄN HỒNG ĐÀO','employee_code'=>'6632','email'=>'vytuong7723@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'NGUYỄN THỊ NHƯ Ý','employee_code'=>'6642','email'=>null,'department'=>'Xưởng sản xuất'],
            ['name'=>'ĐOÀN MAI NHIỀU','employee_code'=>'6645','email'=>'doannhieu2009@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'HỒ VĂN HIẾU ','employee_code'=>'6657','email'=>'hovanhieu1508@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'NGUYỄN HUYỀN TRÂN','employee_code'=>'6663','email'=>'huyentran160620@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'LONG THỊ KIM HỒNG','employee_code'=>'6668','email'=>'hagly678@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'NGUYỄN HOÀNG KHA','employee_code'=>'6674','email'=>null,'department'=>'Xưởng sản xuất'],
            ['name'=>'THẠCH THỊ THANH TUYỀN','employee_code'=>'6684','email'=>'thachtuyen.2005@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'HỒ THỊ CẨM LY','employee_code'=>'6694','email'=>'camlyhothi273@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'THỊ BÉ','employee_code'=>'6703','email'=>'thibe661996@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'DANH HỒNG PHÚC ','employee_code'=>'6704','email'=>'phucdanh3010@gmail.com','department'=>'Phòng QC'],
            ['name'=>'LÔ THỊ THƠM','employee_code'=>'6707','email'=>null,'department'=>'Xưởng sản xuất'],
            ['name'=>'VÕ THỊ THÚY QUYÊN','employee_code'=>'6711','email'=>null,'department'=>'Xưởng sản xuất'],
            ['name'=>'NGUYỄN THỊ YẾN NHI','employee_code'=>'6713','email'=>null,'department'=>'Xưởng sản xuất'],
            ['name'=>'NGUYỄN THỊ KIM TUYẾN','employee_code'=>'6720','email'=>'kimtuyen170522@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'NEÁNG LINH ĐA','employee_code'=>'6726','email'=>null,'department'=>'Xưởng sản xuất'],
            ['name'=>'LÊ MINH TIẾN ','employee_code'=>'6735','email'=>'leminhtien684@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'BAO MỸ TIÊN','employee_code'=>'6736','email'=>'baotien2704@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'NGUYỄN HOÀNG VI','employee_code'=>'6749','email'=>'hoangvihv2007@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'THẠCH THỊ MỸ LIÊM','employee_code'=>'6758','email'=>'myliem1988@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'NGUYỄN MINH THƯ','employee_code'=>'6759','email'=>'minthu100421@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'ĐÀM VĂN QUÝ','employee_code'=>'6760','email'=>'damvanquy.4056@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'NGUYỄN THỊ MỘNG TRÚC','employee_code'=>'6761','email'=>'mongtruc03082006@gmail.com','department'=>'Phòng QC'],
            ['name'=>'NGUYỄN THỊ THƯ HÀ ','employee_code'=>'6763','email'=>'hhanguyenn357@gmail.com','department'=>'Phòng QC'],
            ['name'=>'NGUYỄN THỊ TUYẾT TRINH ','employee_code'=>'6764','email'=>'ntt24trinh@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'LÊ THỊ SÁU NHỎ ','employee_code'=>'6765','email'=>'nhole120389@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'ĐINH THỊ HUYỀN THANH','employee_code'=>'6766','email'=>null,'department'=>'Xưởng sản xuất'],
            ['name'=>'ĐỖ MINH QUỐC ','employee_code'=>'6768','email'=>'dominhquoc05071994@gmail.com','department'=>'Ban Giám đốc'],
            ['name'=>'TRẦN KIM CHI ','employee_code'=>'6775','email'=>'huynhkhen9695@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'ĐẶNG THỊ MỘNG NGHI','employee_code'=>'6776','email'=>'dangthimongnghi0@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'NGUYỄN THỊ TUYẾT NGÂN','employee_code'=>'6778','email'=>'nttn090507@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'PHAN THỊ MỸ DUNG','employee_code'=>'6784','email'=>'Pdung025@gmail.com','department'=>'Phòng QC'],
            ['name'=>'LÂM VĂN TƯỜNG','employee_code'=>'6788','email'=>'tuong02092007@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'NGUYỄN THANH NGA','employee_code'=>'6790','email'=>'maythao0906@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'ĐOÀN THỊ CẨM TÚ ','employee_code'=>'6791','email'=>'camtubdwork@gmail.com','department'=>'Ban Giám đốc'],
            ['name'=>'VÕ THỊ KIM LIÊN','employee_code'=>'6796','email'=>'kimlien19072006@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'ĐINH THỊ DIỄM TRINH','employee_code'=>'6797','email'=>'dtdiemtrinh0707@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'HUỲNH TẤN ĐẠT','employee_code'=>'6799','email'=>null,'department'=>'Xưởng sản xuất'],
            ['name'=>'NGUYỄN QUỲNH NHƯ Ý','employee_code'=>'6802','email'=>'nqnywork2507@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'TRIỆU MỸ MỘNG TRÚC ','employee_code'=>'6831','email'=>'trieumymongtruc@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'ĐẶNG HOÀNG LONG','employee_code'=>'6836','email'=>'longdang091995@gmail.com','department'=>'Phòng QC'],
            ['name'=>'NGUYỄN THỊ XUÂN ','employee_code'=>'6837','email'=>'muaxuanhivong@gmail.com','department'=>'Phòng IT'],
            ['name'=>'NGUYỄN THỊ THÚY','employee_code'=>'6846','email'=>'nguyenthithuy1008986@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'PHẠM THỊ PHƯỚC','employee_code'=>'6848','email'=>'phuocpham238952@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'LÂM XUÂN YẾN ','employee_code'=>'6849','email'=>'lamxuanyen7@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'NGUYỄN NGỌC TRÂN ','employee_code'=>'6850','email'=>'nguyenngoctran.tn10@gmail.com','department'=>'Phòng QC'],
            ['name'=>'NGUYỄN HOÀNG VINH','employee_code'=>'6851','email'=>'hoangvinh180709@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'DANH THANH NGHĨA','employee_code'=>'6852','email'=>'danhthanhnghia52004@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'NGUYỄN THỊ KIM NGÂN','employee_code'=>'6856','email'=>'pengan06052002@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'NGUYỄN THỊ THU LỢI','employee_code'=>'6858','email'=>'ngloi3568@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'TRẦN THỊ MẾN','employee_code'=>'6859','email'=>null,'department'=>'Xưởng sản xuất'],
            ['name'=>'TRẦN MINH SANG','employee_code'=>'6862','email'=>'tranminhsangncc1990@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'NGUYỄN CÔNG TẠI','employee_code'=>'6864','email'=>null,'department'=>'Xưởng sản xuất'],
            ['name'=>'TRẦN THỊ CẨM TÚ','employee_code'=>'6867','email'=>null,'department'=>'Xưởng sản xuất'],
            ['name'=>'TRẦN THỊ THAO','employee_code'=>'6870','email'=>null,'department'=>'Xưởng sản xuất'],
            ['name'=>'NGUYỄN TRÚC DUY','employee_code'=>'6872','email'=>'nguyentrucduy50@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'TIẾT MƠ ','employee_code'=>'6873','email'=>'motiet82@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'HỒ THANH HOÀNG','employee_code'=>'6878','email'=>null,'department'=>'Xưởng sản xuất'],
            ['name'=>'LÊ THỊ THU HIỀN ','employee_code'=>'6882','email'=>'lethuhien9696@gmail.com','department'=>'Phòng QC'],
            ['name'=>'LÊ THỊ NGỌC TRÂM','employee_code'=>'6883','email'=>'luitram12@icloud.com','department'=>'Xưởng sản xuất'],
            ['name'=>'QUÁCH MỘNG MỸ MỸ','employee_code'=>'6884','email'=>'mymyquach387@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'NGUYỄN THỊ NHƯ HUỲNH ','employee_code'=>'6887','email'=>'nhuquynh310107@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'NGUYỄN THỊ HOÀNG TRÚC','employee_code'=>'6888','email'=>'tthanhtruc6737@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'LÊ THỊ HỒNG NGÂN','employee_code'=>'6889','email'=>'hngan24122005@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'LÊ THỊ NGỌC THOẠI','employee_code'=>'6890','email'=>'ltngocthoai@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'NGUYỄN THỊ KIỀU','employee_code'=>'6892','email'=>'nguyenkieu130824@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'NGUYỄN THỊ CÔNG DANH','employee_code'=>'6895','email'=>'congdanhnguyen.01052003@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'LÂM PHAN TÚ TIÊN','employee_code'=>'6897','email'=>'lamtutienst06@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'TỐNG VŨ LINH','employee_code'=>'6898','email'=>'tongvulinh7@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'NGUYỄN HỒNG SƠN','employee_code'=>'6899','email'=>'thaanhson2000@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'NGUYỄN VĂN TRƯƠNG LỞI','employee_code'=>'6901','email'=>'tuvy52003@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'NGUYỄN TUẤN PHONG','employee_code'=>'6902','email'=>'we7dokg@gmail.com','department'=>'Phòng QC'],
            ['name'=>'TỐNG THỊ YẾN NHI','employee_code'=>'6903','email'=>'tongthiyennhisv2007@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'HOÀNG THỊ THƯƠNG','employee_code'=>'6904','email'=>null,'department'=>'Xưởng sản xuất'],
            ['name'=>'DANH NGỌC HUYỀN','employee_code'=>'6905','email'=>'danhngochuyen55@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'THẠCH THỊ NGỌC PHƯƠNG','employee_code'=>'6907','email'=>'pngphuong27@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'LÊ TRƯỜNG GIANG ','employee_code'=>'6908','email'=>'gle0987185@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'LÊ THỊ TRANG','employee_code'=>'6912','email'=>'letrang2101207@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'RMAH H HLĂK','employee_code'=>'6915','email'=>'hlakkrmahh@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'TRƯƠNG THỊ HỜ HÒA','employee_code'=>'6916','email'=>'truongthihohoaa52s@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'DANH THỊ BÍCH VÂN','employee_code'=>'6917','email'=>'tmim7712@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'DANH THỊ CHÚC NỮ','employee_code'=>'6918','email'=>null,'department'=>'Xưởng sản xuất'],
            ['name'=>'DANH LƯU HỒNG THÚY','employee_code'=>'6919','email'=>'th6518658@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'NGUYỄN THỊ HUYỀN TRÂN ','employee_code'=>'6929','email'=>'th5867856@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'PHAN TRUNG KIÊN ','employee_code'=>'6930','email'=>'kienp3146@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'LÝ THỊ NA VY','employee_code'=>'6937','email'=>'navilythi@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'LÝ THỊ NGỌC DIỄM','employee_code'=>'6938','email'=>'lythingocdiem32@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'BÙI KIM TRIỆU','employee_code'=>'6939','email'=>'ngocnghi298@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'TRẦN THỊ NGỌC','employee_code'=>'6940','email'=>'ngoc368052@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'CHÂU THỊ CẨM ĐẸP','employee_code'=>'6941','email'=>'chauthicamdep12062002@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'LÊ ĐÌNH PHÁP','employee_code'=>'6946','email'=>'ledinhphappy@gmail.com','department'=>'Phòng Nhân sự'],
            ['name'=>'ĐẶNG YẾN NHI','employee_code'=>'6948','email'=>'lunll150823@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'ĐẶNG THỊ THÙY TRÂM','employee_code'=>'6949','email'=>'thuytram24032008@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'LÝ THỊ MŨNG','employee_code'=>'6950','email'=>'lythimung8083@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'RMAH H\' ĐON','employee_code'=>'6953','email'=>'rmahdon2001@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'THỊ CHUNG','employee_code'=>'6960','email'=>'thi052193@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'VÕ HOÀNG SƠN','employee_code'=>'6964','email'=>'vohoangson7192@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'HỒ TÚ VI','employee_code'=>'6965','email'=>'hotuvi92003@icloud.com','department'=>'Xưởng sản xuất'],
            ['name'=>'NGUYỄN THỊ THẢO LY','employee_code'=>'6966','email'=>'nguyenthithaoly595@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'NGUYỄN NGỌC HUYỀN','employee_code'=>'6967','email'=>null,'department'=>'Xưởng sản xuất'],
            ['name'=>'ĐỖ HỒNG QUÝ','employee_code'=>'6968','email'=>'dohongquy031@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'NGUYỄN THỊ KIỀU NHƯ','employee_code'=>'6969','email'=>'kieunhunguyenthi31@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'VÕ VĂN VÀNG','employee_code'=>'6970','email'=>'vovanvangcatkhanh@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'PHẠM THỊ THANH HÀ','employee_code'=>'6971','email'=>'haphamthithanh121204@gmail.com','department'=>'Phòng Kinh doanh'],
            ['name'=>'THẠCH SANG','employee_code'=>'6973','email'=>null,'department'=>'Xưởng sản xuất'],
            ['name'=>'NGUYỄN NGỌC TÂM ','employee_code'=>'6974','email'=>null,'department'=>'Xưởng sản xuất'],
            ['name'=>'VÕ VĂN SỰ ','employee_code'=>'6975','email'=>null,'department'=>'Xưởng sản xuất'],
            ['name'=>'VÕ MINH THƯ','employee_code'=>'6976','email'=>null,'department'=>'Ban Giám đốc'],
            ['name'=>'DƯƠNG THÁI TUYẾT BĂNG','employee_code'=>'6977','email'=>null,'department'=>'Xưởng sản xuất'],
            ['name'=>'ĐẶNG NGỌC YẾN','employee_code'=>'6978','email'=>null,'department'=>'Xưởng sản xuất'],
            ['name'=>'NGUYỄN THỊ MAI TRANG','employee_code'=>'6980','email'=>null,'department'=>'Xưởng sản xuất'],
            ['name'=>'HỒ THỊ MỸ LINH ','employee_code'=>'6984','email'=>null,'department'=>'Phòng IT'],
            ['name'=>'HUỲNH THỊ NHƯ QUỲNH','employee_code'=>'6988','email'=>null,'department'=>'Xưởng sản xuất'],
            ['name'=>'NGUYỄN THỊ NGỌC HUYỀN','employee_code'=>'6989','email'=>null,'department'=>'Xưởng sản xuất'],
            ['name'=>'LÂM THỊ ĐÀ RI','employee_code'=>'6990','email'=>null,'department'=>'Xưởng sản xuất'],
            ['name'=>'NGUYỄN THỊ BÉ TÂM','employee_code'=>'6992','email'=>null,'department'=>'Xưởng sản xuất'],
            ['name'=>'NGUYỄN THỊ NHANG','employee_code'=>'6993','email'=>null,'department'=>'Xưởng sản xuất'],
            ['name'=>'LA THỊ VIỀN','employee_code'=>'6994','email'=>null,'department'=>'Xưởng sản xuất'],
            ['name'=>'ĐINH THỊ KIM THOA','employee_code'=>'6995','email'=>null,'department'=>'Xưởng sản xuất'],
            ['name'=>'NGUYỄN THỊ THÚY','employee_code'=>'6996','email'=>null,'department'=>'Xưởng sản xuất'],
            ['name'=>'SO THỊ HÈ','employee_code'=>'6997','email'=>null,'department'=>'Xưởng sản xuất'],
            ['name'=>'LÊ THỊ MỸ LIÊN ','employee_code'=>'6998','email'=>null,'department'=>'Xưởng sản xuất'],
        ];

        $defaultPassword = Hash::make('password');

        foreach ($employees as $emp) {
            User::firstOrCreate(
                ['employee_code' => $emp['employee_code']],
                [
                    'name'                 => $emp['name'],
                    'email'                => $emp['email'],
                    'password'             => $defaultPassword,
                    'role'                 => 'employee',
                    'department'           => $emp['department'],
                    'position'             => null,
                    'annual_leave_balance' => 12,
                ]
            );
        }
    }
}
